http:
  port: 8081
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  products:
    paths: "/products/*"
  orders: 
    paths: "/orders/*"
  payments:
    paths: "/payments/*"
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  productService:
    url: 'http://localhost:4000'
  orderService:
    url: 'http://localhost:4002'
  paymentService:
    url: 'http://localhost:4001'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  orders:
    apiEndpoints:
      - orders
    policies:
      - proxy:
          - action: 
              serviceEndpoint: orderService
  products:
    apiEndpoints:
      - products
    policies:
      - proxy:
          - action: 
              serviceEndpoint: productService
  payments:
    apiEndpoints:
      - payments
    policies:
      - proxy:
          - action: 
              serviceEndpoint: paymentService
